#lang info

(define fg #(#xdc #xdc #xcc))
(define bg-1 #(#x2b #x2b #x2b))
(define bg-5 #(#x38 #x38 #x38))
(define bg #(#x00 #x00 #x00))
(define bg+1 #(#x4f #x4f #x4f))
(define bg+2 #(#x5f #x5f #x5f))
(define bg+3 #(#x6f #x6f #x6f))
(define red+1 #(#xdc #xa3 #xa3))
(define red #(#xff #x00 #x00))
(define red-1 #(#x8b #x00 #x00))
(define red-2 #(#x8b #x00 #x00))
(define red-3 #(#x9c #x63 #x63))
(define red-4 #(#x8c #x53 #x53))
(define red-5 #(#x7F #x07 #x3F))
(define pink #(#xff #x69 #xb4))
(define pink-1 #(#xff #x14 #x93))
(define pink-2 #(#xcd #x10 #x76))
(define orange-2 #(#xFF #x64 #x00))
(define orange-1 #(#xff #x8c #x00)) ; DarkOrange
(define orange #(#xff #xa5 #x00))
(define yellow #(#xff #xff #x00))
(define yellow-1 #(#xFB #xDE #x2D))
(define yellow-2 #(#xd0 #xbf #x8f))
(define yellow-3 #(#xD8 #xFA #x3C))
(define yellow-4 #(#xE9 #xC0 #x62))
(define yellow-5 #(#xff #xd7 #x00))
(define green-2 #(#x00 #x64 #x00))
(define green-1 #(#x2e #x8b #x57))
(define green #(#x00 #xff #x00))
(define green+1 #(#x61 #xCE #x3C))
(define green+2 #(#x9f #xc5 #x9f))
(define green+3 #(#xaf #xd8 #xaf))
(define green+4 #(#xbf #xeb #xbf))
(define cyan #(#x93 #xe0 #xe3))
(define blue+1 #(#x94 #xbf #xf3))
(define blue #(#x00 #x00 #xff)) ; blue
(define blue-1 #(#x7b #x68 #xee)) ; medium slate blue
(define blue-2 #(#x6a #x5a #xcd)) ; slate blue
(define blue-3 #(#xad #xd8 #xe6)) ; light blue
(define blue-4 #(#xb2 #xdf #xee)) ; LightBlue2
(define blue-5 #(#x4c #x83 #xff))
(define blue-6 #(#x96 #xCB #xFE))
(define blue-7 #(#x00 #xff #xff))
(define blue-8 #(#x4F #x94 #xCD))
(define magenta #(#xdc #x8c #xc3))
(define black #(#x00 #x00 #x00))
(define black-2 #(#x0C #x10 #x21))
(define black-3 #(#x0A #x0A #x0A))
(define gray #(#xd3 #xd3 #xd3))
(define gray-2 #(#x8B #x89 #x89))
(define gray-3 #(#x91 #x91 #x91))
(define gray-4 #(#x99 #x99 #x99))
(define gray-5 #(#x33 #x33 #x33))
(define gray-6 #(#x1A #x1A #x1A))
(define gray-7 #(#x4D #x4D #x4D))
(define gray-8 #(#x26 #x26 #x26))
(define white #(#xff #xff #xff))
(define white-2 #(#xF8 #xF8 #xF8))
(define white-3 #(#xff #xfa #xfa))

(define framework:color-schemes
  `(#hash((name . "Cyberpunk")
          (colors
           .
           ((framework:paren-match-color ,blue)
            (framework:syntax-color:scheme:comment ,gray-2)
            (framework:syntax-color:scheme:constant ,blue-5)
            (framework:syntax-color:scheme:error ,red)
            (framework:syntax-color:scheme:hash-colon-keyword ,orange-2)
            (framework:syntax-color:scheme:keyword ,yellow-3)
            (framework:syntax-color:scheme:string ,green+1)
            (framework:syntax-color:scheme:text ,pink)
            (framework:syntax-color:scheme:other ,pink-1)
            (framework:syntax-color:scheme:parenthesis ,fg)
            (framework:syntax-color:scheme:symbol ,fg)
            (drracket:read-eval-print-loop:error-color ,red)
            (drracket:read-eval-print-loop:out-color ,pink-1)
            (drracket:read-eval-print-loop:value-color ,blue-6)
            (drracket:check-syntax:free-variable ,red)
            (drracket:check-syntax:imported ,yellow-3)
            (drracket:check-syntax:lexically-bound ,pink-1)
            (drracket:check-syntax:set!d ,cyan)
            (drracket:check-syntax:unused-require ,red)))
          (white-on-black-base? . #t))))

(define deps '("base"))
